import {
  FaPalette,
  FaCode,
  FaWordpress,
  FaArrowsRotate,
  FaRocket,
  FaLifeRing,
} from "react-icons/fa6";

export const servicesData = [
  {
    icon: FaPalette,
    title: "Website Design",
    desc: "Modern and visually appealing designs tailored to your brand identity and goals.",
    color: "from-[#3D0C99]/20 to-[#00ADE0]/10",
    iconColor: "text-[#3D0C99]",
    border: "border-[#3D0C99]/20",
    highlights: [
      "Brand-aligned visual direction",
      "Responsive wireframes and layouts",
      "Clear user journey planning",
      "Design handoff for development",
    ],
  },
  {
    icon: FaCode,
    title: "Front-End Development",
    desc: "Responsive, lightning-fast websites built with React and Next.js.",
    color: "from-[#00ADE0]/20 to-[#3D0C99]/10",
    iconColor: "text-[#00ADE0]",
    border: "border-[#00ADE0]/20",
    highlights: [
      "Fast loading page experiences",
      "SEO-optimized structure",
      "Accessible interactive UI",
      "Modern component-driven build",
    ],
  },
  {
    icon: FaRocket,
    title: "Performance Optimization",
    desc: "Fast-loading, Core Web Vitals optimized, and SEO-friendly websites.",
    color: "from-[#3D0C99]/20 to-[#00ADE0]/10",
    iconColor: "text-[#3D0C99]",
    border: "border-[#3D0C99]/20",
    highlights: [
      "Image and asset compression",
      "Core Web Vitals improvements",
      "Faster mobile performance",
      "Analytics and tracking setup",
    ],
  },
  {
    icon: FaWordpress,
    title: "WordPress Development",
    desc: "Custom WordPress and Elementor solutions for easy self-management.",
    color: "from-[#00ADE0]/20 to-[#3D0C99]/10",
    iconColor: "text-[#00ADE0]",
    border: "border-[#00ADE0]/20",
    highlights: [
      "Custom themes and templates",
      "Elementor-friendly layouts",
      "Easy content editing workflows",
      "Secure maintenance foundation",
    ],
  },
  {
    icon: FaArrowsRotate,
    title: "Website Redesign",
    desc: "Transform outdated websites into modern, high-performing experiences.",
    color: "from-[#3D0C99]/20 to-[#00ADE0]/10",
    iconColor: "text-[#3D0C99]",
    border: "border-[#3D0C99]/20",
    highlights: [
      "Fresh visual refresh",
      "Content hierarchy improvements",
      "Conversion-focused updates",
      "Improved navigation flow",
    ],
  },
  {
    icon: FaLifeRing,
    title: "Maintenance & Support",
    desc: "Reliable website updates, monitoring, and ongoing technical support.",
    color: "from-[#00ADE0]/20 to-[#3D0C99]/10",
    iconColor: "text-[#00ADE0]",
    border: "border-[#00ADE0]/20",
    highlights: [
      "Ongoing updates and fixes",
      "Monitoring and backups",
      "Fast issue resolution",
      "Scalable support plans",
    ],
  },
];
