import {
  FaPalette,
  FaCode,
  FaWordpress,
  FaArrowsRotate,
  FaRocket,
  FaLifeRing,
} from "react-icons/fa6";

export const servicesData = [
  {
    icon: FaPalette,
    title: "Website Design",
    desc: "Custom-designed sites that match your brand — not a recycled template. We map out your visitor's journey before we design a single pixel.",
    color: "from-[#3D0C99]/20 to-[#00ADE0]/10",
    iconColor: "text-[#3D0C99]",
    border: "border-[#3D0C99]/20",
    highlights: [
      "Brand-matched color, type, and layout system",
      "Wireframes mapped to your customer's actual journey",
      "Fully responsive design (mobile, tablet, desktop)",
    ],
  },
  {
    icon: FaCode,
    title: "Front-End Development",
    desc: "Built with React and Next.js for speed and reliability. No bloated page builders slowing your site down.",
    color: "from-[#00ADE0]/20 to-[#3D0C99]/10",
    iconColor: "text-[#00ADE0]",
    border: "border-[#00ADE0]/20",
    highlights: [
      "Component-based build for easy future updates",
      "Sub-2-second page load targets",
      "Cross-browser and cross-device testing",
      "Clean, documented code you actually own",
    ],
  },
  {
    icon: FaRocket,
    title: "Performance Optimization",
    desc: "Sites that load in under 2 seconds and are structured for Google from day one — not bolted on after launch.",
    color: "from-[#3D0C99]/20 to-[#00ADE0]/10",
    iconColor: "text-[#3D0C99]",
    border: "border-[#3D0C99]/20",
    highlights: [
      "Core Web Vitals audit and fixes",
      "Image compression and lazy loading",
      "On-page SEO: titles, meta tags, headings, schema markup",
      "Google Analytics & Search Console setup",
    ],
  },
  {
    icon: FaWordpress,
    title: "WordPress Development",
    desc: "Custom WordPress sites you can update yourself, without needing a developer for every text change.",
    color: "from-[#00ADE0]/20 to-[#3D0C99]/10",
    iconColor: "text-[#00ADE0]",
    border: "border-[#00ADE0]/20",
    highlights: [
      "Custom Elementor templates matched to your brand",
      "Editable sections for your team (no code needed)",
      "Security hardening and plugin cleanup",
      "Fast-loading WordPress builds (most WP sites are bloated — ours aren't)",
    ],
  },
  {
    icon: FaArrowsRotate,
    title: "Website Redesign",
    desc: "A modern rebuild of your outdated site that keeps the SEO rankings you've already earned.",
    color: "from-[#3D0C99]/20 to-[#00ADE0]/10",
    iconColor: "text-[#3D0C99]",
    border: "border-[#3D0C99]/20",
    highlights: [
      "Full audit of your current site's weak points",
      "SEO equity preservation (no lost rankings)",
      "Modernized design and improved navigation",
      "Conversion-focused rewrite of key pages",
    ],
  },
  {
    icon: FaLifeRing,
    title: "Maintenance & Support",
    desc: "Ongoing updates, monitoring, and fixes so your site stays fast and secure after launch.",
    color: "from-[#00ADE0]/20 to-[#3D0C99]/10",
    iconColor: "text-[#00ADE0]",
    border: "border-[#00ADE0]/20",
    highlights: [
      "Monthly backups and uptime monitoring",
      "Plugin/dependency updates",
      "Bug fixes within 48 hours",
      "Small content updates included",
    ],
  },
];
